### ISSUE TITLE
Source code highlighting for chatbot.

### ISSUE THREAD

**Issue by gopinaath** [aws-solutions/generative-ai-application-builder-on-aws#36]
**Is your feature request related to a problem? Please describe.**
When I ask the chatbot to write code for a specific need, the source code response is not readable.  

**Describe the feature you'd like**
I'd like source response to be formatted and highlighted based on language syntax.  While there are situations where I can use code whisperer or equivalent solutions, having good code highlighting capability within this solution will be very helpful.

**Additional context**
Readable response to technical source code questions.

**Comment by ihmaws** [comment]
Hi @gopinaath, thanks for the request.

I'm not sure what version of the solution you are on, but code syntax highlighting and other forms of markdown has been supported by the solution as of `v1.1.0`. Below is an example generated on `v1.2.0` of the solution:
<img width="1870" alt="image" src="https://github.com/aws-solutions/generative-ai-application-builder-on-aws/assets/111378641/e552b153-2912-4d0c-a676-4cde10979fde">

As you can see above, the generated code snippet was rendered within a code block with the appropriate syntax highlighting for python. So my first recommendation would be to install the latest version of the solution in the event you are on a version <`v1.1.0`.

If you are on a supported version, the next reason it may not be working is due to the response provided by the LLM. The chat interface is not performing any specialized logic to manually detect code and render it as necessary. We simply take in valid markdown from the LLM and render as is.

So if the LLM responds appropriately and wraps the code snippet in a valid markdown code block such as:

\``` _code_language_ 
    *my_code_here*
     ...
\```
then the chat UI will show it as in the screenshot above. If you are getting the code block but no syntax highlighting, then the LLM is not adding the `code_language`. If you aren't getting code blocks at all, then the llm is not adding the backticks  **\```**

These are LLM specific limitations, so experiment with each of the different LLMs to see which works best for code generation use cases (the example above was generated using Claude v2.1 with a temperature setting of 1).

Hope that helps! Please let me know of any follow up questions or if I misunderstood the feature request.

**Comment by ihmaws** [comment]
Unfortunately, there is no way for to **force** it.

Personally, I've found that if in your message you clearly ask for a code snippet/example, and specify the programming language you want it in, that helps.

You can also try some more advanced prompting techniques such as [few-shot prompting](https://docs.aws.amazon.com/bedrock/latest/userguide/general-guidelines-for-bedrock-users.html#optimize-prompts-for-text-models) to give the LLM some examples of how to format code samples. This may help a bit in examples where you are seeing it's not doing a good job.

_Also, as a quick warning, a bug introduced in v1.2.0 may prevent a direct upgrade from your current version to the latest. If this is the case, please deploy a fresh stack to leverage these new features. We are investigating the bug and are hoping to resolve upgrade failures in a future release. Sorry for the inconvenience._
